Dodanie archiwum projektów i drobna zmiana navbara
KNR-PW/knr-pw.github.io pull request #18
Opened 2023-07-21 02:17 UTC by KaNoSki

Teoretycznie skończone i kod sprawdzony.

Nie wiem jak działa to menu nawigacyjne na telefonie i ekranach dotykowych, przydało by się jakoś sprawdzić. 
Ewentualnie zrobić za pomocą JSa funkcję kliknięcia.

Wszelkie porady i uwagi co do stylu i ułożenia mile widziane.

TODO
- [ ] dodać jakieś inne zdjęcia jako img do archiwum na stronie głównej
- [ ] sprawdzenie czy "Więcej" w navbarze dobrze działa z ekranami dotykowymi

2023-07-21 15:57 UTC, pktiuk commented
Jeśli chodzi o wygląd na dotykowych urządzeniach to wystarczy zwęzić okno przeglądarki.
![image](https://github.com/KNR-PW/knr-pw.github.io/assets/45544416/510a4c3f-55c6-4d6f-9706-8ee5b2743d7a)
Na moje oko przycisk Archiwum jest za blisko

A jeśli chodzi o sam dotyk to nie działa on tak jak trzeba (mam dotykowego lapka). Klikając na `Więcej` rozwijam listę i pojawia się `Archiwum`. Kiedy znowu klikam na więcej nic się nie dzieje, ale kiedy klikam na `Archiwum` to te menu się zwija i znika.

2023-07-21 15:59 UTC, pktiuk commented on layouts/index.html
> +              <path fill="#c0bdbd" d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A60
Pamiętaj usunąć tą część

2023-07-21 17:33 UTC, pktiuk commented
![Zrzut ekranu z 2023-07-21 18-01-00](https://github.com/KNR-PW/knr-pw.github.io/assets/45544416/33661356-f707-4287-899f-2c0ab83dd147)

Poza tym po twoich zmianach chyba zepsuły się te białe paseczki

2023-07-21 17:39 UTC, pktiuk commented on layouts/index.html
> +        </div>
Tutaj bym chyba pozbył się tego obrazka.   

Można tak nieco bardziej minimalistycznie napisać. coś w stylu.    
`Jeśli jesteś ciekawy innych naszych projektów możesz zajrzeć do naszego archiwum. `

2023-07-21 17:40 UTC, pktiuk requested changes
Sam  wygląd strony archiwum bardzo mi się podoba.

2023-07-22 08:12 UTC, pktiuk commented
Widzę, że masz konflikty z mainem.  
Spróbuj zrobić rebase

2023-07-22 10:34 UTC, KaNoSki commented on layouts/index.html
> +        </div>
https://github.com/KNR-PW/knr-pw.github.io/pull/18/commits/66b449ff1f7692300fec8be5d758fcbae2e357ba

2023-07-22 13:02 UTC, pktiuk commented on layouts/index.html
> +        </div>
Jeszcze bym wyrzucił ten obrazek obok archiwum.

![image](https://github.com/KNR-PW/knr-pw.github.io/assets/45544416/84791f0c-de47-441a-836d-d192eb26eef2)
(tylko jeszcze jakoś wyśrodkuj jakoś na stronie).

2023-07-22 16:32 UTC, KaNoSki commented on layouts/index.html
> +        </div>
https://github.com/KNR-PW/knr-pw.github.io/pull/18/commits/fb2f6c563c630f470a480a231f6422addb8fe6cd

2023-07-23 12:04 UTC, pktiuk commented on layouts/partials/header.html
> +                    <a href="/#archive" class="navbar-link" id="archive-page">Archiwum</a>
```suggestion
                    <a href="/project" class="navbar-link" id="archive-page">Archiwum</a>
```
Tak będzie lepiej

2023-07-23 12:07 UTC, pktiuk commented on static/css/style.css
>      top:0;
Jeśli uważasz, że ta część jest niepotrzebna to możesz ją po prostu usunąć.

2023-07-23 12:10 UTC, pktiuk requested changes
Mam kilka czysto kosmetycznych uwag. Poza tym można już będzie mergować.

2023-07-23 13:34 UTC, pktiuk commented on layouts/index.html
> +              <a href="#archive" class="archive__item-btn">
Popsułeś teraz ten przycisk, po nigdzie on nie przenosi

2023-07-23 13:36 UTC, pktiuk commented on layouts/index.html
> +              <a href="#archive" class="archive__item-btn">
```suggestion
              <a href="/project" class="archive__item-btn"> 
```

2023-07-23 16:30 UTC, pktiuk approved these changes
Merguję

2023-07-23 16:31 UTC, merged