badge-haczyk: JS obsługujący stan badge'ów
KNR-PW/knr-pw.github.io pull request #44
Opened 2024-03-03 13:50 UTC by LukPogo

Oryginalny issue: 
https://github.com/KNR-PW/hangwatch/issues/17

Dodałem kod, który co pewien interwał pobiera z serwera informację o statusie każdego z haczyków o odpowiednim ID:
![image](https://github.com/KNR-PW/knr-pw.github.io/assets/153677792/e4718c3e-38cd-4aa6-a405-a4b9e4958214)

Dodane ID wygląda tak:
![image](https://github.com/KNR-PW/knr-pw.github.io/assets/153677792/86289eee-f592-4a0a-b0ef-a6f89645982b)

Co ważne do testowania skorzystałem ze zmodyfikowanej wersji serwera, która wyświetla statyczne informacje:
![image](https://github.com/KNR-PW/knr-pw.github.io/assets/153677792/adc72382-f703-41c8-9a55-8a6e6b5e9a67)
![image](https://github.com/KNR-PW/knr-pw.github.io/assets/153677792/73842e5c-d96b-409d-ba35-83d88ebed8a2)

Oto jedne z możliwych konfiguracji:

- Jako domyślne ustawienie w footerze, wszystkie są wyłączone:
![image](https://github.com/KNR-PW/knr-pw.github.io/assets/153677792/93002f86-d1d9-4b71-b462-d0cf780a924b)

- Na wszystkich haczykach wiszą klucze:
![image](https://github.com/KNR-PW/knr-pw.github.io/assets/153677792/d3b2f19a-5080-481a-9b8c-4fe9851d0270)

- Tylko na jednym wisi klucz:
![image](https://github.com/KNR-PW/knr-pw.github.io/assets/153677792/bb7dcb40-0b4c-48df-869f-2f92c4d60f1a)

- Dwa pracują normalnie, natomiast jeden z trzech napotkał błąd (np.: nie mógł jako jedyny połączyć się z serwerem):
![image](https://github.com/KNR-PW/knr-pw.github.io/assets/153677792/57a341b3-351a-4d31-bd53-9ffbabfcd1ee)

- Przy napotkaniu błędu po próbie zfetchowania, wszystkie badge zmieniają kiolor na czerwony (np.: gdy serwer nie odpowiada):
![image](https://github.com/KNR-PW/knr-pw.github.io/assets/153677792/5b647bc0-e236-4686-9522-fbab7a4a3e81)
![image](https://github.com/KNR-PW/knr-pw.github.io/assets/153677792/8c071d27-fdb2-4aa8-a1cb-9430623bc0cf)

2024-03-03 14:15 UTC, pktiuk commented on static/js/badge.js
> +
W wypadku errora borze by było też coś wyprintować w konsoli. `console.log`

2024-03-03 14:17 UTC, pktiuk commented on static/js/badge.js
> +                const stan = data[key].state;
Nazwy zmiennych  powinny być po angielsku.

2024-03-03 14:20 UTC, pktiuk commented on static/js/badge.js
> +                element.className='haczyk_right';
Po co jest ta linijka?

2024-03-03 14:21 UTC, pktiuk commented on static/js/badge.js
> +                }
Zmianę stanu przycisku lepiej przenieść do oddzielnej funkcji. 

jakaś funkcja w stylu `updateButtonState(element_id, current_state)` byłaby na miejscu.

2024-03-03 14:22 UTC, pktiuk requested changes
Wstępnie nieźle to wygląda.

Mam kilka drobnych pooprawek, ale ogólnie wszystko na plus

2024-03-04 16:23 UTC, pktiuk commented
Wszystko działa ładnie przetestowałem, kiedy ktoś był w kole

2024-03-04 16:57 UTC, pktiuk commented on layouts/partials/footer.html
> +                  </div>
Na ten moment mamy haczyk tylko w sali 027 ;)

2024-03-05 17:20 UTC, LukPogo commented
@pktiuk mam nadzieję, że poprawnie zaadresowałem treść poprawek

2024-03-05 18:10 UTC, pktiuk commented on static/js/badge.js
> +    fetch('hangwatch.knr.edu.pl/hooks')
Popełniłeś tutaj błąd. 
```suggestion
    fetch('https://hangwatch.knr.edu.pl/hooks')
```

2024-03-05 18:13 UTC, merged

2024-03-05 18:13 UTC, pktiuk commented
Dobra robota